%% Empirical part of Huggett, Ventura & Yaron (2006)
% You first need to download data from PSID (explained in second section of
% codes), then this will import the data and run the whole empirical analysis.


%% HVY2006, Section 2.1 describes the data used
% Uses PSID data on earnings, 1969-1992 family files
% Earnings of male household heads
% Ages 20 to 58 (inclusive)
% Restrict sample to those with strictly positive earnings
% Exclude the survey of economic opportunities (SEO) sample which is a
% subsample of the PSID that oversamples the poor.
%
% Broad sample: all males who are currently working, temporarily laid off,
% looking for work but currently unemployed, students, but does not include
% retirees.
% Narrow sample: equals the broad sample, less those unemployed or
% temporarily laid off
% [Since the results are not sensitive to the choice of sample the paper
% presents the results for the broad sample.]
%
% Given all the above sample selection criteria, the average and standard
% deviation of the number of observations per panel-year are 2137 and 131,
% respectively.

if ~exist('figure_c','var')
    figure_c=0; % Normally this will be created by HuggettVenturaYaron2006.m, which calls this HVY2006_DataWork.m script. This is just so that you can run HVY2006_DataWork independently if you want.
end
if ~exist('CreateFigures','var')
    CreateFigures=1; % Normally this will be created by HuggettVenturaYaron2006.m, which calls this HVY2006_DataWork.m script. This is just so that you can run HVY2006_DataWork independently if you want.
end

%% Download the data from PSID, then import
% Go to PSID and look for previous "carts"
% https://simba.isr.umich.edu/DC/c.aspx
% Search for and download the cart called 
% "325247 - HVY2006" associated with the email address "robertdkirkby@gmail.com"
% This will download a zip file, unzip it and put the files in the same
% folder as this current m-file.
% Rename the file which is .sps to _sps.txt
% Rename the file which is _format.sps to _formate_sps.txt
% (if you don't rename these ImportPSIDdata will just give a warning telling you to do so)
% Then the following line of code will import that PSID data
MyPSIDdataset=ImportPSIDdata('J325247');

% Reading the PSID documentation we learn that:
% Whether or not family is in SEO is based on data variable "Family Number"
% Let's do a fully described example of creating a binary variable indicating SEO

% MyPSIDdataset is a structure containing both the data and all the indentifying info 
% We look at it
MyPSIDdataset % shows variables (by code)
% We happen to already have learnt that V3 is the famile number
MyPSIDdataset.V3
% We can see there it is the 1968 Family Number, the 'etext' explains what
% the interpretation is, and 'value' contains all the actual data
% In the 'etext' we read that values <3000 are the main sample, and higher
% than this is the SEO sample.
% The original MyPSIDdataset.V3.value are strings
% There is also an autogenerated attempt to turn these into numbers
% in 'value2' and we will use this
% We cannot just use MyPSIDdataset.V3.value2<=3000 because of how the
% values are set up (it only lists family number for some, not all)
% Instead I found family number 5001 is in column 9978
% And last main sample family seems to be 2930 in column 9536
% Double-checked there is not family 2931
% So I end up using
MainSampleIndicator=[ones(1,9600),zeros(1,length(MyPSIDdataset.V3.value2)-9600)]; % Note: has to be <=3000, as if I tried to create SEOIndicator using >3000 it would not handle NaN in the way I want

% Now we just grab the rest of the relevant data as a panel
% We want earnings, looking through the first few variables we see that V74
% has the etext: {'(Labor part of farm income and business income, wages, bonuses, 
% overtime, commissions, professional practice, labor part of income from roomers and 
% boarders or business income (See editing instructions).)'}
% So we want this variable in this and other years. 
% Easiest way to figure out the other years is going to the PSID website
% data search for variables
% https://simba.isr.umich.edu/DC/s.aspx
% We can search for V74 (make sure to tick the boxes below for PSID family-level and 1968)
% We can click the "i" info button next to V74 (in search results) and
% there is a field in what opens up that says
% "Years Available: 	[68]V74 [69]V514 [70]V1196 [71]V1897 [72]V2498 [73]V3051 [74]V3463 [75]V3863 
% [76]V5031 [77]V5627 [78]V6174 [79]V6767 [80]V7413 [81]V8066 [82]V8690 [83]V9376 [84]V11023 [85]V12372 
% [86]V13624 [87]V14671 [88]V16145 [89]V17534 [90]V18878 [91]V20178 [92]V21484 ..."
% So now we know all the variable names for earnings in each year [all of which were added to the cart we downloaded]
Earnings=[MyPSIDdataset.V74.value2; MyPSIDdataset.V514.value2; MyPSIDdataset.V1196.value2; MyPSIDdataset.V1897.value2; MyPSIDdataset.V2498.value2;...
    MyPSIDdataset.V3051.value2; MyPSIDdataset.V3463.value2; MyPSIDdataset.V3863.value2; MyPSIDdataset.V5031.value2; MyPSIDdataset.V5627.value2;...
    MyPSIDdataset.V6174.value2; MyPSIDdataset.V6767.value2; MyPSIDdataset.V7413.value2; MyPSIDdataset.V8066.value2; MyPSIDdataset.V8690.value2;...
    MyPSIDdataset.V9376.value2; MyPSIDdataset.V11023.value2; MyPSIDdataset.V12372.value2; MyPSIDdataset.V13624.value2; MyPSIDdataset.V14671.value2;...
    MyPSIDdataset.V16145.value2; MyPSIDdataset.V17534.value2; MyPSIDdataset.V18878.value2; MyPSIDdataset.V20178.value2; MyPSIDdataset.V21484.value2;...
    ];

% Now we also need the "employment status" (which is telling us about "who are currently working, 
% temporarily laid off, looking for work but currently unemployed, students, but does not include retirees.")
% Years Available: 	[68]V196 [69]V639 [70]V1278 [71]V1983 [72]V2581 [73]V3114 [74]V3528 [75]V3967 
% [76]V4458 [77]V5373 [78]V5872 [79]V6492 [80]V7095 [81]V7706 [82]V8374 [83]V9005 [84]V10453 [85]V11637 
% [86]V13046 [87]V14146 [88]V15154 [89]V16655 [90]V18093 [91]V19393 [92]V20693 ..."
EmploymentStatus=[MyPSIDdataset.V196.value2; MyPSIDdataset.V639.value2; MyPSIDdataset.V1278.value2; MyPSIDdataset.V1983.value2; MyPSIDdataset.V2581.value2;...
    MyPSIDdataset.V3114.value2; MyPSIDdataset.V3528.value2; MyPSIDdataset.V3967.value2; MyPSIDdataset.V4458.value2; MyPSIDdataset.V5373.value2;...
    MyPSIDdataset.V5872.value2; MyPSIDdataset.V6492.value2; MyPSIDdataset.V7095.value2; MyPSIDdataset.V7706.value2; MyPSIDdataset.V8374.value2;...
    MyPSIDdataset.V9005.value2; MyPSIDdataset.V10453.value2; MyPSIDdataset.V11637.value2; MyPSIDdataset.V13046.value2; MyPSIDdataset.V14146.value2;...
    MyPSIDdataset.V15154.value2; MyPSIDdataset.V16655.value2; MyPSIDdataset.V18093.value2; MyPSIDdataset.V19393.value2; MyPSIDdataset.V20693.value2;...
    ];

% And we want the age of the household head, V117 is one of them, and from PSID website we get
% "Years Available: 	[68]V117 [69]V1008 [70]V1239 [71]V1942 [72]V2542 [73]V3095 [74]V3508 [75]V3921 
% [76]V4436 [77]V5350 [78]V5850 [79]V6462 [80]V7067 [81]V7658 [82]V8352 [83]V8961 [84]V10419 [85]V11606 
% [86]V13011 [87]V14114 [88]V15130 [89]V16631 [90]V18049 [91]V19349 [92]V20651 ..."
AgeOfHead=[MyPSIDdataset.V117.value2; MyPSIDdataset.V1008.value2; MyPSIDdataset.V1239.value2; MyPSIDdataset.V1942.value2; MyPSIDdataset.V2542.value2;...
    MyPSIDdataset.V3095.value2; MyPSIDdataset.V3508.value2; MyPSIDdataset.V3921.value2; MyPSIDdataset.V4436.value2; MyPSIDdataset.V5350.value2;...
    MyPSIDdataset.V5850.value2; MyPSIDdataset.V6462.value2; MyPSIDdataset.V7067.value2; MyPSIDdataset.V7658.value2; MyPSIDdataset.V8352.value2;...
    MyPSIDdataset.V8961.value2; MyPSIDdataset.V10419.value2; MyPSIDdataset.V11606.value2; MyPSIDdataset.V13011.value2; MyPSIDdataset.V14114.value2;...
    MyPSIDdataset.V15130.value2; MyPSIDdataset.V16631.value2; MyPSIDdataset.V18049.value2; MyPSIDdataset.V19349.value2; MyPSIDdataset.V20651.value2;...
    ];

% Gender of household head (so can restrict sample to males), V119 is one of them, and from PSID website we get
% Years Available: 	[68]V119 [69]V1010 [70]V1240 [71]V1943 [72]V2543 [73]V3096 [74]V3509 [75]V3922 
% [76]V4437 [77]V5351 [78]V5851 [79]V6463 [80]V7068 [81]V7659 [82]V8353 [83]V8962 [84]V10420 [85]V11607 
% [86]V13012 [87]V14115 [88]V15131 [89]V16632 [90]V18050 [91]V19350 [92]V20652 ..."
GenderOfHead=[MyPSIDdataset.V119.value2; MyPSIDdataset.V1010.value2; MyPSIDdataset.V1240.value2; MyPSIDdataset.V1943.value2; MyPSIDdataset.V2543.value2;...
    MyPSIDdataset.V3096.value2; MyPSIDdataset.V3509.value2; MyPSIDdataset.V3922.value2; MyPSIDdataset.V4437.value2; MyPSIDdataset.V5351.value2;...
    MyPSIDdataset.V5851.value2; MyPSIDdataset.V6463.value2; MyPSIDdataset.V7068.value2; MyPSIDdataset.V7659.value2; MyPSIDdataset.V8353.value2;...
    MyPSIDdataset.V8962.value2; MyPSIDdataset.V10420.value2; MyPSIDdataset.V11607.value2; MyPSIDdataset.V13012.value2; MyPSIDdataset.V14115.value2;...
    MyPSIDdataset.V15131.value2; MyPSIDdataset.V16632.value2; MyPSIDdataset.V18050.value2; MyPSIDdataset.V19350.value2; MyPSIDdataset.V20652.value2;...
    ];

sizeonevariable=size(MyPSIDdataset.V119.value2);
Year=(1968:1:1992)'*ones(sizeonevariable);

% Because of how I restrict the sample I also want an indicator for the individual
IndividualIndicator=ones(25,1)*(1:1:length(MyPSIDdataset.V3.value2));


%% Create the sample used by HVY2006
% We have earnings
% First, an indicator for ages 20 to 58
% Actually, it is for 18 to 60, as it turns out HVY2006 use 5 year bins
% around each age when they calculate earnings percentiles
I1=(18<=AgeOfHead).*(AgeOfHead<=60);
% I1=(20<=AgeOfHead).*(AgeOfHead<=58);
% Second, an indicator of male
I2=(GenderOfHead==1); % 1 is male, 2 is female, 9 is NA
% Third, an indicator for "currently working, temporarily laid off,
% looking for work but currently unemployed, students, but does not include retirees"
I3A=(EmploymentStatus==1)+(EmploymentStatus==2)+(EmploymentStatus==5); % 1=Working now, or laid off only temporarily, 2=Unemployed, 3=Retired, permanently disabled, 4=Housewife, 5=Student, 6=Other
% Or in the narrow sample, "equals the broad sample, less those unemployed or temporarily laid off"
I3B=(EmploymentStatus==1)+(EmploymentStatus==5);
% Fourth, exclude the SEO sample
I4=MainSampleIndicator;
% Fifth, those with strictly positive earnings
I5=(Earnings>0);
% Sixth, While I download all the 1968 data, HVY2006 only use 1969-1992. So impose that restriction
I6=(Year>=1969).*(Year<=1992);


% So indicators for the broad and narrow restricted samples are
I_broad=logical(I1.*I2.*I3A.*I4.*I5.*I6);
I_narrow=logical(I1.*I2.*I3B.*I4.*I5.*I6);

% Broad sample
BroadSample.Earnings=Earnings(I_broad);
BroadSample.Age=AgeOfHead(I_broad);
BroadSample.Year=Year(I_broad);
BroadSample.Individual=IndividualIndicator(I_broad);

% Narrow sample
NarrowSample.Earnings=Earnings(I_narrow);
NarrowSample.Age=AgeOfHead(I_narrow);
NarrowSample.Year=Year(I_narrow);
NarrowSample.Individual=IndividualIndicator(I_narrow);

% Get get an idea how restrictive each of these is
sum(sum(I1))
sum(sum(I2))
sum(sum(I3A))
sum(sum(I4)).*25 % Note: misleading to just sum(sum(I4)) as it only has household dimension, missing the year dimension
sum(sum(I5))
sum(sum(I_broad))

% Look again
sum(sum(I1.*I4))
sum(sum(I2.*I4))
sum(sum(I3A.*I4))
sum(sum(I5.*I4))
sum(sum(I_broad))
% Looks like age of head is the most restrictive thing here
% Look at marginal contributions of other others after we impose main sample and age 
sum(sum(I1.*I4))
sum(sum(I2.*I4.*I1))
sum(sum(I3A.*I4.*I1))
sum(sum(I5.*I4.*I1))
sum(sum(I_broad))
% Yeah, almost all of resticting the sample comes from main sample (not SEO) and age of head.


%% First check that we match that
% the "average and standard deviation of the number of observations per panel-year are 2137 and 131"

% There are 25 years, so the average number of observations per panel-year is
fprintf('Average number of observations per panel-year is %5.0f \n', numel(BroadSample.Earnings)/25)
% Not same as HVY2006, but close

% I cannot see what the difference might be? (except I start in 1968 and
% they say they start 1969 (HVY2006, pg X), but it seems weird they would
% drop the first year of PSID without any obvious reason for doing so)
% [Dropping 1968 does not make it same as they have]

[cnt_unique, ~] = hist(BroadSample.Year,unique(BroadSample.Year));
fprintf('The standard deviation of the number of observations per panel year is %5.0f \n', std(cnt_unique))

% Note, if I were to drop first decade, the later years are much closer to
% the average and std dev reported by HVY2006.
% I cannot see why there is a difference between what I have and HVY2006.
% Maybe I am missing something, but not clear what?

% One possibility, in Section 2.2, they do 5 year age bins. "Real values
% are calculated using the CPI. To calculate e^p_{j,t} we use a 5 year bin
% centered at age j. For example, to calculate earnings percentiles of
% agents age j=30 in year t=1980 we use data on agents age 28-32 in 1980.
% We also use a 5 year bin centered at ages 20 and 58. To do this we use
% data on agets age 18-22 and 56-60."
% So maybe their counts of number of observations are actually on ages 18-60?

% When I do the sample restriction as 18-60 I get much closer to what
% HVY2006 report. 
% (Excluding 1968 actually is further away from HVY2006, but only miniscule amount)


%% Construction of age-profiles
% Time to plot the age-profiles, reproducing Figures 1 and 2

% Figure 1, Panel A: Mean earnings (conditional on age)
% Figure 1, Panel B: Gini coeff of earnings (conditional on age)
% Figure 1, Panel C: Mean/Median of earnings (conditional on age)
% Figure 2: Percentiles of earnings (conditional on age)

% First, we need to convert nominal earnings into real earnings.
% HVY2006 say they do this using CPI
CPI=getFredData('CPIAUCSL','1968-01-01','1992-12-31','lin','a','avg');
% I will use 1969-1992 data, and renormalize CPI so that 1969=1
CPIdata=CPI.Data(2:end)./CPI.Data(2);
% Now use this to get real earnings
BroadSample.RealEarnings=zeros(size(BroadSample.Earnings));
for aa=1:length(BroadSample.Earnings)
    BroadSample.RealEarnings(aa)=BroadSample.Earnings(aa)/CPIdata(BroadSample.Year(aa)-1968);
end

% First step is to create e^p_{j,t}, the data percentiles
% Section 2.2 of HVY2006: "To calculate e^p_{j,t} we use a 5 year bin
% centered at age j. For example, to calculate earnings percentiles of
% agents age j=30 in year t=1980 we use data on agents age 28-32 in 1980.
% We also use a 5 year bin centered at ages 20 and 58. To do this we use
% data on agets age 18-22 and 56-60."
MaxObs=1000; % Just a guess, but each year has only 2000-ish observations, so seems like this should be way more than in a 5-age bin for a given year
RealEarnings_jjtt=nan(MaxObs,58-19,1992-1968);
Counter_jjtt=zeros(58-19,1992-1968);
for aa=1:length(BroadSample.RealEarnings)
    tt=BroadSample.Year(aa)-1968;
    for jj=20:58
        if BroadSample.Age(aa)>=(jj-2) && BroadSample.Age(aa)<=(jj+2) % age is appropriate
            Counter_jjtt(jj-19,tt)=Counter_jjtt(jj-19,tt)+1;
            RealEarnings_jjtt(Counter_jjtt(jj-19,tt),jj-19,tt)=BroadSample.RealEarnings(aa);
        end
    end
end
% We have all the data set up appropriately, now we need to calculate the percentiles
ptiles=[2.5,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,92.5,95,97.5,99]; % HVY2006 calculate these 23 percentiles
earningspercentile_jjtt=nan(length(ptiles),58-19,1992-1968);
for jj=20:58
    for tt=1969:1992
        earningspercentile_jjtt(:,jj-19,tt-1968)=prctile(RealEarnings_jjtt(:,jj-19,tt-1968),ptiles);
    end
end

% Second step is to regress log earnings percentiles on age and cohort effects
J=58-19;
T=1992-1968;
AgeFixedEffects=zeros(J,T,J); % J variables (each column) which each have J*T observations (the rows)
for jj=1:J
    AgeFixedEffects(jj,:,jj)=1;
end
AgeFixedEffects=reshape(AgeFixedEffects,[J*T,J]);
Ncohorts=J+(T-1); % cohort is effectively just age minus year
CohortFixedEffects=zeros(J,T,Ncohorts);
for jj=1:J
    for tt=1:T
        CohortFixedEffects(jj,tt,jj-tt+T)=1; % cohort is just age minus year [the T is youngest jj in last tt gives index of 1]
    end
end
CohortFixedEffects=reshape(CohortFixedEffects,[J*T,Ncohorts]);

% Cohort-fixed-effect regression
B=zeros(J,length(ptiles)); % store all the ptiles coeffs here
for pp=1:length(ptiles)
    ydata=reshape(earningspercentile_jjtt(pp,:,:),[(58-19)*(1992-1968),1]);
    Xdata=[AgeFixedEffects,CohortFixedEffects];
    b = regress(ydata,Xdata);
    B(:,pp)=b(1:J); % b is (J+Ncohorts)-by-1
end

% Finally, we plot the fitted age effects
% HVY2006: "More specifically, we plot beta^p_j e^p_40 / beta^p_40, where
% e^p_40 is the geometric average real earnings at age 40 and percentile p
% in the data. We then scale all profiles by a common factor normalized to
% mean earnings to 100."
% I don't understand what "geometric average real earnings at age 40 and
% percentile p" means? There is not a lot of data around each percentile,
% so I don't really understand what it is that the geometric mean is being
% taken of?
B=B.*mean(earningspercentile_jjtt(:,40-19,:),3)'./B(40-19,:);
ptilemass=[3.75,3.75,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,3.75,2.5,2.5,2,1.75]/100; % (This is explained below, I copy-pasted it up to here)
MeanEarnings=sum(sum(B.*ptilemass,2))/(58-19);
% Not clear what weight is given to each age to get "normalized to mean
% earnings to 100" so I have applied equal weights to each age. [Not
% very important, as is just normalization anyway]
B=100*B/MeanEarnings;

% Plot the percentiles (the eight of them that HVY2006 show in their figure 2)
% ptiles=[2.5,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,92.5,95,97.5,99];
% Here: 5, 10, 25, 50, 75, 90, 95, 99
if CreateFigures==1
    figure_c=figure_c+1;
    figure(figure_c)
    plot(20:1:58,B(:,2))
    hold on
    plot(20:1:58,B(:,3))
    plot(20:1:58,B(:,6))
    plot(20:1:58,B(:,11))
    plot(20:1:58,B(:,16))
    plot(20:1:58,B(:,19))
    plot(20:1:58,B(:,21))
    plot(20:1:58,B(:,23))
    hold off
    title('Earnings percentiles (0.05 to 0.99) - PSID data')
    legend('p=0.05','p=0.10','p=0.25','p=0.50','p=0.75','p=0.90','p=0.95','p=0.99','location','northwest')
end

% Now we plot the mean, gini coeff, and mean/median.
% HVY2006 "The findings in Fig 1a-c are all calculated directly from the
% results graphed in Fig 2"
% Median is trivial, it is just the 50-th percentile
Fig1_Median=B(:,11);
% Mean, we do percentile value times relevant mass.
% Define the masses for our 23 percentiles
% ptilemass=[3.75,3.75,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,3.75,2.5,2.5,2,1.75]/100;
% ptilemid=[0,(ptiles(2:end)-ptiles(1:end-1))/2+ptiles(1:end-1),100];
% ptilemass=ptilemid(2:end)-ptilemid(1:end-1); % Gives the same
Fig1_Mean=sum(B.*ptilemass,2);
% To compute the Gini from percentiles, we treat them like a lorenz curve
LorenzCurve=cumsum(B.*ptilemass,2)./sum(B.*ptilemass,2); % Note: divide by total
% Gini is A/(A+B) (A is area between diagonal and lorenz, B is area under lorenz)
GiniA=sum((ptiles/100-LorenzCurve).*ptilemass,2);
GiniB=sum(LorenzCurve.*ptilemass,2);
Fig1_Gini=GiniA./(GiniA+GiniB);

if CreateFigures==1
    figure_c=figure_c+1;
    figure(figure_c)
    subplot(3,1,1); plot(20:1:58,Fig1_Mean)
    title('Panel A: Mean Earnings')
    xlabel('Age')
    subplot(3,1,2); plot(20:1:58,Fig1_Gini)
    title('Panel B: Dispersion (Gini coefficient)')
    xlabel('Age')
    ylim([0,0.45])
    subplot(3,1,3); plot(20:1:58,Fig1_Mean./Fig1_Median)
    title('Panel C: Skewness (Mean/Median')
    xlabel('Age')
    ylim([0,1.4])
end
% Looking good so far :D
% Small differences from HVY2006, but given number of observations differ
% it is very close.


%% Alternative views of age effects
% Redo, but instead of cohort fixed effects, we will instead use time fixed
% effects. HVY2006 also do a 'cohort effect plus restricted time fixed effect'
% but I don't repeat it here (as it is no longer a simple OLS, and because
% it gives essentially the same result anyway).

TimeFixedEffect=zeros(J,T,T-1); % T-1 variables (each column) which each have J*T observations (the rows)
for tt=1:T-1
    TimeFixedEffect(:,tt,tt)=1;
end
TimeFixedEffect=reshape(TimeFixedEffect,[J*T,T-1]);
% Have to use only T-1 variables here

% Time-fixed-effect regression
B2=zeros(J,length(ptiles)); % store all the ptiles coeffs here
for pp=1:length(ptiles)
    ydata=reshape(earningspercentile_jjtt(pp,:,:),[(58-19)*(1992-1968),1]);
    Xdata=[AgeFixedEffects,TimeFixedEffect];
    b2 = regress(ydata,Xdata);
    B2(:,pp)=b2(1:J); % b is (J+T)-by-1
end

% Do the same treatment of results before plotting as previously
B2=B2.*mean(earningspercentile_jjtt(:,40-19,:),3)'./B2(40-19,:);
MeanEarnings=sum(sum(B2.*ptilemass,2))/(58-19);
% Not clear what weight is given to each age to get "normalized to mean
% earnings to 100" so I have applied equal weights to each age. [Not
% very important, as is just normalization anyway]
B2=100*B2/MeanEarnings;


% TFE=time fixed effect
Fig3_TFE_Median=B2(:,11);
Fig3_TFE_Mean=sum(B2.*ptilemass,2);
LorenzCurve=cumsum(B2.*ptilemass,2)./sum(B2.*ptilemass,2); % Note: divide by total
GiniA=sum((ptiles/100-LorenzCurve).*ptilemass,2);
GiniB=sum(LorenzCurve.*ptilemass,2);
Fig3_TFE_Gini=GiniA./(GiniA+GiniB);

if CreateFigures==1
    figure_c=figure_c+1;
    figure(figure_c)
    subplot(3,1,1); plot(20:1:58,Fig1_Mean,20:1:58,Fig3_TFE_Mean)
    title('Panel A: Mean Earnings')
    xlabel('Age')
    subplot(3,1,2); plot(20:1:58,Fig1_Gini,20:1:58,Fig3_TFE_Gini)
    title('Panel B: Dispersion (Gini coefficient)')
    xlabel('Age')
    ylim([0,0.45])
    subplot(3,1,3); plot(20:1:58,Fig1_Mean./Fig1_Median, 20:1:58,Fig3_TFE_Mean./Fig3_TFE_Median)
    title('Panel C: Skewness (Mean/Median')
    xlabel('Age')
    ylim([0,1.4])
    legend('Cohort FE','Time FE','location','southeast')
end
% Again, close but not identical to HVY2006 (likely because the underlying
% sample is close but not identical)



%% Done. Time for the model!


